services:
  postgres:
    image: postgres:16
    container_name: postgres_db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  fastapi:
    build: .
    container_name: fastapi_app
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - /var/www/static:/var/www/static
    depends_on:
      - postgres
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"
    command: ["redis-server", "--replicaof", "no", "one"]
    volumes:
      - redis_data:/data

volumes:
  redis_data:
    name: redis_data
